select goodscode,
    "goodsCodeHistory",
    registeredproductname,
    registeredmedicinemodel,
    registeredoutlook,
    goodsname,
    realitymedicinemodel,
    realityoutlook,
    materialname,
    factor,
    minunit,
    unit,
    "traceCodeFlag",
    companynamesc,
    "nameOrLhoder",
    subpackager,
    approvalcode,
    "oldApprovalCode",
    goodsstandardcode,
    productinsurancetype,
    productcode,
    productname,
    productmedicinemodel,
    productremark,
    "businessLicense",
    "drugValidityDate",
    "isChildDrugs",
    "isOtc"
from {table_name}
where version = '{batch_number}'
;
